drop table IF EXISTS statistics;

CREATE TABLE IF NOT EXISTS statistics
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app             varchar(50),
    uri             varchar(500),
    ip              varchar(20),
    timestamp_stat  TIMESTAMP WITHOUT TIME ZONE,

    constraint EndpointHit_PK
        primary key (id)
);

